### ISSUE TITLE
hash

### ISSUE THREAD

**Issue by ThomasAndreatta** [RedBita/redbita.github.io#1]
Add somewhere:
For the active machine you'll need the root hash:
Linux: root:$6${YIFGN9YscCV72BjFtx/tehbc7sQTJp09c5.}:18277:0:99999:7:::
Windows:admin::xxxxxx:xxxxxxx:{xxxxxxx}

the things into {} have to be written in red and the brackets removed

**Comment by Sebo-the-tramp** [comment]
Done
